### ISSUE TITLE
optimize README.md

### ISSUE THREAD

**Issue by jianxiapyh** [ILLIXR/ILLIXR-docker#4]
suggest using 'xhost -local:root' instead of 'xhost +local:root'
reorganize the documentation flow

**Comment by jianxiapyh** [comment]
oh also, I think we  need at least one text editor pre-installed in this docker

**Comment by mhuzai** [comment]
+1 to what Yihan said.

I think the order of sections in `README.md` should be the following. I've also added comments after each section.
- Features
- Prerequisites. Do we need "Docker" in the list since the NVIDIA guide takes care of it? And Docker Compose should probably be here, right?
- Creating The Container --> Using Prebuilt Image. The following headings should be just steps.
    - One-Line Command --> Launch container. Give the Docker Compose command here as an alternative. Btw, why does `/tmp/.X11-unix` need to be mounted and why twice? Also, should we run with `--rm` so that it gets removed automatically after shutdown?
    - Access container. This should specify how to connect to the container.
    - Is My Setup Working? --> Verify that your setup is working.
    - Launching prebuilt ILLIXR. The `illixr-runner` instruction is not required because the runner takes care of it.
    - Launching a custom version of ILLIXR. Please add an example showing usage of the `-v` flag.
- Building The Image --> Building Your Own Image

**Comment by shg8** [comment]
Changed the organization of the README as suggested. Also installed vim in the container.
